###

POST http://localhost:3000/tags
Content-Type: application/json

{
  "name": "java",
  "slug": "nestjs-fundamentals-java",
  "description": "Everything you need to know about NestJS core concepts",
  "schema": {
    "@context": "https://schema.org",
    "@type": "Thing",
    "name": "NestJS Tag",
    "description": "Tag for NestJS tutorials"
  },
  "featuredImageUrl": "https://images.example.com/nestjs-tag.jpg"
}